---
default_install_hook_types:
  - pre-commit
  - commit-msg
default_stages:
  - pre-commit
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: check-symlinks
      - id: fix-byte-order-marker
      - id: no-commit-to-branch
        args: [--branch, main]
      - id: end-of-file-fixer
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.17.0
    hooks:
      - id: gitleaks
  - repo: https://github.com/commitizen-tools/commitizen
    rev: 3.5.3
    hooks:
      - id: commitizen
        stages:
          - commit-msg
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.45.0
    hooks:
      - id: eslint
        files: \.[jg]s?$  # *.js, *.gs
        types: [file]
        additional_dependencies:
          - eslint@latest
          - eslint-plugin-import@latest
          - eslint-plugin-n@latest
          - eslint-plugin-promise@latest
          - eslint-config-standard@latest
